{{- if and .Values.ingress.tls.enabled .Values.ingress.tls.certManager.enabled }}
{{- $host := index .Values.ingress.hosts 0 }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "rustfs.fullname" . }}-tls
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ .Values.ingress.tls.secretName }}
  issuerRef:
    name: {{ .Values.ingress.tls.certManager.issuer.name }}
    kind: {{ .Values.ingress.tls.certManager.issuer.kind }}
  dnsNames:
    - {{ $host.host }}
{{- end }}
