{{- if .Values.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rustfs.fullname" . }}-tls
type: kubernetes.io/tls
data:
  tls.crt : {{ .Values.tls.crt | b64enc | quote }}
  tls.key : {{ .Values.tls.key | b64enc | quote }}
{{- end }}