{{- if .Values.mode.distributed.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rustfs.fullname" . }}-headless
  labels:
    {{- include "rustfs.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- /* headless service */}}
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: {{ .Values.service.ep_port }}
      name: endpoint
    - port: {{ .Values.service.console_port }}
      name: console
  selector:
    {{- include "rustfs.selectorLabels" . | nindent 4 }}
{{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rustfs.fullname" . }}-svc
  {{- if .Values.mode.distributed.enabled }}
  {{- if eq .Values.ingress.className "traefik" }}
  {{- with .Values.ingress.traefikAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- end }}
  labels:
    {{- include "rustfs.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.enabled }}
  type: ClusterIP
  {{- else }}
  type: {{ .Values.service.type }}
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  {{- end }}
  ports:
    - port: {{ .Values.service.ep_port }}
      name: endpoint
    - port: {{ .Values.service.console_port }}
      name: console
  selector:
    {{- include "rustfs.selectorLabels" . | nindent 4 }}
