{{- if and .Values.gatewayApi.enabled (empty .Values.gatewayApi.existingGateway.name) }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "rustfs.fullname" . }}-gateway
spec:
  gatewayClassName: {{ .Values.gatewayApi.gatewayClass }}
  {{- with .Values.gatewayApi.listeners }}
  listeners:
  {{- if .web }}
    - name: http
      port: {{ .web.port }}
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Same
  {{- end }}
  {{- if .websecure }}
    - name: https
      port: {{ .websecure.port }}
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: {{ include "rustfs.fullname" $ }}-tls
            kind: Secret
  {{- end }}
  {{- end }}
{{- end }}
