{{- if and .Values.gatewayApi.enabled (eq .Values.gatewayApi.gatewayClass "traefik") }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "rustfs.fullname" . }}-route
spec:
  parentRefs:
  {{- if .Values.gatewayApi.existingGateway.name }}
    - name: {{ .Values.gatewayApi.existingGateway.name }}
      {{- if .Values.gatewayApi.existingGateway.namespace }}
      namespace: {{ .Values.gatewayApi.existingGateway.namespace }}
      {{- end }}
      sectionName: https
  {{- else }}
    - name: {{ include "rustfs.fullname" . }}-gateway
      sectionName: https
  {{- end }}
  hostnames:
    - {{ .Values.gatewayApi.hostname }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "rustfs.fullname" . }}-sticky-svc
          port: {{ .Values.service.console.port }}
          kind: TraefikService
          group: traefik.io

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "rustfs.fullname" . }}-redirect
spec:
  parentRefs:
  {{- if .Values.gatewayApi.existingGateway.name }}
    - name: {{ .Values.gatewayApi.existingGateway.name }}
      {{- if .Values.gatewayApi.existingGateway.namespace }}
      namespace: {{ .Values.gatewayApi.existingGateway.namespace }}
      {{- end }}
      sectionName: http
  {{- else }}
    - name: {{ include "rustfs.fullname" . }}-gateway
      sectionName: http
  {{- end }}
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
{{- end }}