{{- if .Values.mtls.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "rustfs.fullname" . }}-server-tls
spec:
  secretName: {{ include "rustfs.fullname" . }}-server-tls
  issuerRef:
    name: {{ include "rustfs.fullname" . }}-ca-issuer
    kind: Issuer
  commonName: {{ include "rustfs.fullname" . }}-cluster
  dnsNames:
    - "*.rustfs-headless"
    - "*.rustfs-headless.rustfs.svc.cluster.local"
    - rustfs-svc.rustfs.svc.cluster.local
    - xiaomage-ai.cloud
    - "*.xiaomage-ai.cloud"
  usages:
    - server auth
{{- end }}