[observability]
endpoint = "http://localhost:4317" # 可观测性数据上报的终端地址，默认为"http://localhost:4317"
use_stdout = true                  # 是否将日志输出到标准输出
sample_ratio = 2.0                 # 采样率，表示每 2 条数据采样 1 条
meter_interval = 30                # 指标收集间隔，单位为秒
service_name = "rustfs"            # 服务名称，用于标识当前服务
service_version = "0.1.0"          # 服务版本号
environment = "develop"           # 运行环境，如开发环境 (develop)
logger_level = "debug"             # 日志级别，可选 debug/info/warn/error 等
local_logging_enabled = true       # 是否启用本地 stdout 日志记录，true 表示启用，false 表示禁用

#[[sinks]]                      # Kafka 接收器配置
#type = "Kafka"                   # 是否启用 Kafka 接收器，默认禁用
#brokers = "localhost:9092" # Kafka 服务器地址
#topic = "logs"                     # Kafka 主题名称
#batch_size = 100                   # 批处理大小，每次发送的消息数量
#batch_timeout_ms = 1000           # 批处理超时时间，单位为毫秒

#[[sinks]]                   # Webhook 接收器配置
#type = "Webhook"                    # 是否启用 Webhook 接收器
#endpoint = "http://localhost:8080/webhook" # Webhook 接收地址
#auth_token = ""                    # 认证令牌
#batch_size = 100                   # 批处理大小
#batch_timeout_ms = 1000           # 批处理超时时间，单位为毫秒

[[sinks]]                       # 文件接收器配置
type = "File"                      # 是否启用文件接收器
path = "./deploy/logs/rustfs.log" # 日志文件路径
buffer_size = 10                    # 缓冲区大小，表示每次写入的字节数
flush_interval_ms = 100           # 批处理超时时间，单位为毫秒
flush_threshold = 100          # 刷新阈值，表示在达到该数量时刷新日志

[logger]                           # 日志器配置
queue_capacity = 10                # 日志队列容量，表示可以缓存的日志条数