apiVersion: v2
name: rustfs
description: RustFS helm chart to deploy RustFS on kubernetes cluster.
type: application
version: 0.0.77
appVersion: "1.0.0-alpha.77"
home: https://rustfs.com
icon: https://media.sys.truenas.net/apps/rustfs/icons/icon.svg
maintainers:
- name: RustFS, Inc.
  url: https://github.com/rustfs/rustfs/tree/main/helm/rustfs
sources:
- https://github.com/rustfs/rustfs
